export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    SELECT_ORG: "/auth/select-org",
    ME: "/auth/me",
    LOGOUT: "/auth/logout",
    REGISTER: "/auth/signup",
    REFRESH: "/auth/refresh-token",
    PROFILE: "/auth/profile",
    AVATAR: "/auth/avatar",
    EMPLOYEE_AVATAR: "/hr/employees/me/avatar",
    CHANGE_PASSWORD: "/auth/change-password",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    PERMISSIONS: "/auth/me/permissions",
    VERIFY_EMAIL: "/auth/verify-email",
    RESEND_VERIFICATION: "/auth/resend-verification",
    ACCEPT_INVITE: "/auth/accept-invite",
    ADMIN_RESET: (id) => `/hr/employees/${id}/reset-password`,
  },

  TWO_FA: {
    STATUS: "/auth/2fa/status",
    SETUP: "/auth/2fa/setup",
    CONFIRM: "/auth/2fa/confirm",
    VERIFY: "/auth/2fa/verify",
    DISABLE: "/auth/2fa/disable",
    REGEN_BACKUP: "/auth/2fa/backup-codes/regenerate",
  },

  ORG: {
    BASE: "/organizations",
    PROFILE: "/org/profile",
    USERS: "/org/users",
    CREATE: "/auth/create-org",
    ENABLED_MODULES: (orgId) => `/modules/enabled`,
    LOGO: "/org/logo",
    SETUP_STATUS: "/org/setup/status",
    SETUP_SECURITY: "/org/setup/security",
  },
  HR: {
    DASHBOARD_WIDGETS: {
      NEW_HIRES: "/hr/employees/dashboard/new-hires",
      BIRTHDAYS: "/hr/employees/dashboard/birthdays",
      TODAY_ATTENDANCE: "/hr/employees/dashboard/today-attendance",
    },
    DASHBOARD: "/hr/employees/dashboard",
    CORE: {
      EMPLOYEES: "/hr/employees",
      BRANCHES: "/hr/branches",
      SHIFTS: "/hr/shifts",
      EMPLOYEE_LIST: "/hr/employees/list",
      EMPLOYEE_DETAIL: (id) => `/hr/employees/${id}`,
      TRANSFER: (id) => `/hr/employees/${id}/transfer`,
      PROMOTE: (id) => `/hr/employees/${id}/promote`,
      CONFIRM: (id) => `/hr/employees/${id}/confirm`,
      EXIT: (id) => `/hr/employees/${id}/exit`,
      EMPLOYEES_ME: "/hr/employees/me",
      EMPLOYEES_ME_ASSETS: "/hr/employees/me/assets",
      EMPLOYEES_ME_PAYSLIPS: "/hr/employees/me/payslips",
      EMPLOYEES_ME_LEAVE_SUMMARY: "/hr/employees/me/leave-summary",
      EMPLOYEES_ME_ATTENDANCE_SUMMARY: "/hr/employees/me/attendance-summary",
      EMPLOYEES_ME_DASHBOARD: "/hr/employees/me/dashboard",
      EMPLOYEE_STATS: (id) => `/hr/employees/${id}/stats`,
      EMPLOYEE_TEAM: (id) => `/hr/employees/${id}/team`,
      ID_CARD: (id) => `/hr/employees/${id}/id-card`,
      UPDATE_PERMISSIONS: (id) => `/hr/employees/${id}/permissions`,
      UPDATE_ROLE: (id) => `/hr/employees/${id}/role`,
      DOCUMENTS: (id) => `/hr/employees/${id}/documents`,
      DOCUMENT_DETAIL: (id, docId) => `/hr/employees/${id}/documents/${docId}`,
      ORG_CHART: "/hr/employees/org-chart",
      ID_FORMAT: "/hr/employees/id-format",
      IMPORT_TEMPLATE: "/hr/employees/import/template",
      IMPORT_VALIDATE: "/hr/employees/import/validate",
      IMPORT_CONFIRM: "/hr/employees/import/confirm",
      RESEND_INVITE: (id) => `/hr/employees/${id}/resend-invite`,
      EMPLOYEES_EXPORT: "/hr/employees/export",
      DEPARTMENTS: "/hr/departments",
      DEPARTMENT_DETAIL: (id) => `/hr/departments/${id}`,
      DESIGNATIONS: "/hr/designations",
      DESIGNATION_DETAIL: (id) => `/hr/designations/${id}`,
      DEPARTMENTS_TREE: "/hr/departments/tree",
      ROLES: "/hr/roles",
      ROLE_DETAIL: (id) => `/hr/roles/${id}`,
      ROLES_PERMISSIONS: "/hr/roles/permissions",
      SHIFTS: "/hr/shifts",
      SHIFT_DETAIL: (id) => `/hr/shifts/${id}`,
      SHIFT_ASSIGN: (employeeId) => `/hr/shifts/assign/${employeeId}`,
      SHIFT_BULK_ASSIGN: "/hr/shifts/bulk-assign",
      HOLIDAYS: "/hr/holidays",
      HOLIDAY_DETAIL: (id) => `/hr/holidays/${id}`,
      HOLIDAYS_BULK: "/hr/holidays/bulk",
      ATTENDANCE_POLICY: "/hr/settings/attendance-policy",
      SETTINGS: "/hr/settings",
      SETTING_DETAIL: (key) => `/hr/settings/${key}`,
      SETTINGS_PUBLIC: "/hr/settings/public",
      AUDIT_LOGS: "/hr/audit",
      AUDIT_HISTORY: (module, entityId) => `/hr/audit/${module}/${entityId}`,
      AUDIT_EXPORT: "/hr/audit/export",
      AUDIT_META: "/hr/audit/meta",
      OFFBOARDING_LIST: "/hr/employees/offboard_list",

    },
    ATTENDANCE: {
      TODAY: "/hr/attendance/today",
      CHECKIN: "/hr/attendance/checkin",
      CHECKOUT: "/hr/attendance/checkout",
      LIST: "/hr/attendance",
      ME: "/hr/attendance/me",
      REPORT: "/hr/attendance/report",
      EXPORT: "/hr/attendance/export",
      MANUAL: "/hr/attendance/manual",
      FILTERS: ({ employeeId, dateFrom, dateTo, departmentId }) => {
        const params = new URLSearchParams();

        if (employeeId) params.append("employeeId", employeeId);
        if (dateFrom) params.append("dateFrom", dateFrom);
        if (dateTo) params.append("dateTo", dateTo);
        if (departmentId) params.append("departmentId", departmentId);

        return `/hr/attendance/filters?${params.toString()}`;
      },
      REGULARIZATION: "/hr/attendance/regularization",
      REGULARIZATION_LIST: "/hr/attendance/regularization",
      REGULARIZATION_BY_EMPLOYEE: (id) => `/hr/attendance/regularization/${id}`,
      REGULARIZATION_APPROVE: (id) =>
        `/hr/attendance/regularization/${id}/approve`,
      REGULARIZATION_REJECT: (id) =>
        `/hr/attendance/regularization/${id}/reject`,
    },
    LEAVE: {
      ME: "/hr/leave/me",
      BASE: "/hr/leave",
      POLICIES: "/hr/leave/types",
      ENTITLEMENTS: "/hr/leave/entitlements",
      BALANCE_ME: "/hr/leave/balance/me",
      PENDING_APPROVALS: "/hr/leave/pending-approvals",
      CALENDAR: "/hr/leave/calendar",
      CALANDER_EXPORT: "/hr/leave/calendar/export.ics",
      BALANCE: "/hr/leave/balance",
      ENCASH: "/hr/leave/encash",
    },
    PAYROLL: {
      BASE: "/hr/payroll",
      RUN: "/hr/payroll/run",
      SUMMARY: (month) => `/hr/payroll/summary/${month}`,
      LIST: (params) => `/hr/payroll?${params}`,
      APPROVE_MONTH: (month) => `/hr/payroll/approve/${month}`,
      PAY_MONTH: (month) => `/hr/payroll/pay/${month}`,
      DETAIL: (id) => `/hr/payroll/${id}`,
      APPROVE_SINGLE: (id) => `/hr/payroll/${id}/approve`,
      PAY_SINGLE: (id) => `/hr/payroll/${id}/pay`,
      OVERRIDE_SINGLE: (id) => `/hr/payroll/${id}/override`,
      PAYSLIP: (id) => `/hr/payroll/${id}/payslip`,
      DOWNLOAD: (id) => `/hr/payroll/${id}/download`,
      COMPONENTS: "/hr/payroll/components",
      COMPONENT_DETAIL: (id) => `/hr/payroll/components/${id}`,
      STRUCTURES: "/hr/payroll/structures",
      STRUCTURES_LIST: "/hr/payroll/all/structures",
      STRUCTURE_DETAIL: (id) => `/hr/payroll/structures/${id}`,
      STRUCTURE_ASSIGN: (id, empId) =>
        `/hr/payroll/structures/${id}/assign/${empId}`,
      LOANS: "/hr/payroll/loans",
      LOAN_DETAIL: (id) => `/hr/payroll/loans/${id}`,
      LOAN_APPROVE: (id) => `/hr/payroll/loans/${id}/approve`,
      LOAN_REJECT: (id) => `/hr/payroll/loans/${id}/reject`,
      REIMBURSEMENTS: "/hr/payroll/reimbursements",
      TAX_CONFIG: "/hr/payroll/tax-config",
      TAX_CONFIG_ACTIVE: "/hr/payroll/tax-config/active",
      TAX_CONFIG_DETAIL: (id) => `/hr/payroll/tax-config/${id}`,
      TAX_CONFIG_ACTIVATE: (id) => `/hr/payroll/tax-config/${id}/activate`,
    },
    PERFORMANCE: {
      GOALS: "/hr/performance/goals",
      APPRAISALS: "/hr/performance/appraisals",
    },
    ASSETS: {
      BASE: "/hr/assets",
      ME: "/hr/assets/me",
    },
    ANNOUNCEMENTS: {
      BASE: "/hr/announcements",
    },
  },
  CHAT: {
    CHANNELS: "/chat/channels",
    CHANNEL_DETAIL: (id) => `/chat/channels/${id}`,
    CHANNEL_MESSAGES: (id) => `/chat/channels/${id}/messages`,
    CHANNEL_ARCHIVE: (id) => `/chat/channels/${id}/archive`,
    CHANNEL_JOIN: (id) => `/chat/channels/${id}/join`,
    CHANNEL_LEAVE: (id) => `/chat/channels/${id}/leave`,
    CHANNEL_MEMBERS: (id) => `/chat/channels/${id}/members`,
    CHANNEL_MEMBER_DETAIL: (id, userId) =>
      `/chat/channels/${id}/members/${userId}`,
    CHANNEL_READ: (id) => `/chat/channels/${id}/read`,
    CHANNEL_PINNED: (id) => `/chat/channels/${id}/pinned`,
    DMS: "/chat/dms",
    DM_GROUP: "/chat/dms/group",
    DM_DETAIL: (id) => `/chat/dms/${id}`,
    DM_MESSAGES: (id) => `/chat/dms/${id}/messages`,
    DM_HIDE: (id) => `/chat/dms/${id}/hide`,
    DM_READ: (id) => `/chat/dms/${id}/read`,
    MESSAGES: "/chat/messages",
    MESSAGE_DETAIL: (id) => `/chat/messages/${id}`,
    MESSAGE_REACT: (id) => `/chat/messages/${id}/react`,
    MESSAGE_PIN: (id) => `/chat/messages/${id}/pin`,
    UNREAD: "/chat/unread",
    SEARCH: "/chat/search",
    UPLOAD: "/chat/upload",
    SEARCH_USER: "/org/users", // Legacy alias
    MEMBERS: "/chat/members",

    // Calls API
    CALL_MEMBERS: "/calls/members",
    CALL_START: "/calls/start",
    CALL_ACCEPT: (id) => `/calls/${id}/accept`,
    CALL_DECLINE: (id) => `/calls/${id}/decline`,
    CALL_END: (id) => `/calls/${id}/end`,
    GROUP_CALL_START: "/calls/group/start",
    CALL_JOIN: (id) => `/calls/${id}/join`,
    CALL_TOKEN: "/calls/token",
    HUDDLE: (channelId) => `/calls/huddle/${channelId}`,
    HUDDLE_JOIN: (channelId) => `/calls/huddle/${channelId}/join`,
    HUDDLE_LEAVE: (channelId) => `/calls/huddle/${channelId}/leave`,
    CALL_HISTORY: "/calls/history",
    CALL_ACTIVE: "/calls/active",

    // Legacy aliases (keep for backward compatibility)
    GET_GROUPS: "/chat/channels",
    CHAT_CONVERSATIONS: "/chat/dms",
    UPLOAD_IMAGES: "/chat/upload",
    UPLOAD_MEDIA: "/chat/upload",
    CREATE_GROUP: "/chat/channels",
    LEAVE_GROUP: "/chat/channels",
    ADD_GROUP_MEMBERS: "/chat/channels",
    REMOVE_GROUP_MEMBER: "/chat/channels",
    PRIVATE_CHAT: "/chat/dms",
    CHAT_MESSAGES: "/chat/messages",
  },
  SUBSCRIPTIONS: {
    CATALOGUE: "/modules/catalogue",
    CATEGORIES: "/modules/catalogue/categories",
    CATALOGUE_DETAIL: (moduleKey) => `/modules/catalogue/${moduleKey}`,
    ORG_STATUS: (orgId) => `/modules/org/${orgId}`,
    INSTALL_PAGE: (orgId) => `/modules/org/${orgId}/install-page`,
    ENABLE: (orgId) => `/modules/org/${orgId}/enabled`,
    START_TRIAL: (orgId) => `/modules/org/${orgId}/start-trial`,
    DISABLE: (orgId) => `/modules/org/${orgId}/disable`,
    UPDATE: (orgId) => `/modules/org/${orgId}/update`,
    BILLING_SUMMARY: (orgId) => `/modules/org/${orgId}/billing`,
    BULK_VISIBILITY: (orgId) =>
      `/modules/org/${orgId}/subscriptions/bulk-visibility`,
    INDIVIDUAL_VISIBILITY: (orgId, moduleKey) =>
      `/modules/org/${orgId}/subscriptions/${moduleKey}/visibility`,
  },
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    STATS: "/admin/stats",
    ACTIVITY: "/admin/activity",
  },
  CRM: {
    DASHBOARD: "/crm/dashboard",
    INIT: "/crm/init",
    PIPELINE: "/crm/pipelines",
    PIPELINE_ID: (id) => `/crm/pipelines/${id}`,
    LEADS: "/crm/leads",
    DEALS_STAGESID: `/crm/deals/stages-summary`,
    KANBAN: `/crm/deals/kanban`,
    LEADS_ID: (id) => `/crm/leads/${id}`,
    LEAD_ATTACHMENTS: (id) => `/crm/leads/${id}/attachments`,
    LEAD_ATTACHMENT_ITEM: (id, attachmentId) => `/crm/leads/${id}/attachments/${attachmentId}`,

    DEALS: "/crm/deals",
    COMPANIES: "/crm/companies",
    CONTACTS: "/crm/contacts",
    ACTIVITY: "/crm/activities",
    ACTIVITY_ID: (id) => `/crm/activities/${id}`,
    ACTIVITY_LIST: "/crm/dashboard/activity-list",
    // TIMELINE_ENTITY: (entity, id) => `/crm/${entity}s/${id}/timeline`,
    TIMELINE: (entityType, entityId) =>
      `/crm/timeline/${entityType}/${entityId}`,
    NOTE: "/crm/notes",
    NOTE_ID: (id) => `/crm/notes/${id}`,

    NOTES_BY_ENTITY: (entityType, entityId) =>
      `/crm/notes?entityType=${entityType}&entityId=${entityId}`,
    // NOTE_ID: (id) => `/crm/notes/${id}`,
    // NOTES_BY_ENTITY: (entityType, entityId) =>
    //   `/crm/notes?entityType=${entityType}&entityId=${entityId}`,
    // 
    BULK: {
      LEADS: {
        ASSIGN: "/crm/bulk/leads/assign",
        STATUS: "/crm/bulk/leads/status",
        DELETE: "/crm/bulk/leads/delete",
      },
      DEALS: {
        STAGE: "/crm/bulk/deals/stage",
        ASSIGN: "/crm/bulk/deals/assign",
      },
      CONTACTS: {
        ASSIGN: "/crm/bulk/contacts/assign",
        DELETE: "/crm/bulk/contacts/delete",
      },
    },
    PRODUCT: "/crm/products",
    IMPORT_CSV: "/crm/leads/import",
    IMPORT_TEMPLATE_ROUTE: "/crm/leads/import/template",
    AUTOMATION: "/crm/automations",
    SETTINGS: "/crm/settings",
    TASK_GROUPS: "/crm/tasks/groups",
    TASK_DASHBOARD: "/crm/tasks/dashboard",
    TASK_DASHBOARD_STATS: "/crm/tasks/dashboard/stats",
    TASK_GROUPS_ID: (id) => `/crm/tasks/groups/${id}`,
    TASK_GROUPS_NAME: (id) => `/crm/tasks/groups/${id}/groupName`,
    TASK_GROUPS_PIN: (id) => `/crm/tasks/groups/${id}/pin`,
    TASKS: "/crm/tasks",
    TASK_ID: (id) => `/crm/tasks/${id}`,
    TASK_PIN: (id) => `/crm/tasks/${id}/pin`,
    TASK_STATUS: (id) => `/crm/tasks/${id}/status`,
  },
  ACCOUNTING: {
    DASHBOARD: "/accounting/dashboard",
    ACCOUNTS: "/accounting/accounts",
    ACCOUNT_DETAIL: (id) => `/accounting/accounts/${id}`,
    INVOICES: "/accounting/invoices",
    PAYMENTS: "/accounting/payments",
    EXPENSES: "/accounting/expenses",
    REPORTS: "/accounting/reports",
    TAX_CONFIGS: "/accounting/taxes",
  },
  BILLING: {
    DASHBOARD: "/billing/dashboard",
    STATUS: "/billing/status",
    SUMMARY: (orgId) => `/billing/summary/${orgId}`,
    INVOICES: "/billing/invoices",
    COMPARE_PLANS: "/billing/plan/compare",
    CHECKOUT: "/billing/checkout",
    UPDATE_SEATS: "/billing/seats",
    SEAT_HISTORY: "/billing/seats/history",
    BILLING_PLAN: "/billing/plan",
    CANCEL_PLAN: "/billing/plan/cancel",
    REACTIVATE_PLAN: "/billing/plan/reactivate",
    PORTAL: "/billing/portal",
    GRANT_TRIAL: "/billing/plan/grant-trial",
    COUPON_VALIDATE: "/billing/coupon/validate",
    UPDATE_CYCLE: "/billing/cycle",
    UPDATE_DATE: "/billing/date",
    BILLING_HISTORY: "/billing/history",
    PAYMENT_METHODS: "/billing/payment-methods",
    PAYMENT_METHOD_BY_ID: (id) => `/billing/payment-methods/${id}`,
    SETUP_INTENT: "/billing/payment-methods/setup-intent",
    DEFAULT_CARD: (id) => `/billing/payment-methods/${id}/default`,
    CANCEL_PENDING_CYCLE: "/billing/pending-cycle",
  },
  CUSTOM_FIELDS: {
    SCHEMA: (moduleName) => `/custom-fields/schema?module=${moduleName}`,
    VALUES: "/custom-fields/values",
    VALUES_FILE: "/custom-fields/values/file",
    VALUESID: (moduleName, id) =>
      `/custom-fields/values?module=${moduleName}&entityId=${id}`,
    GROUPS: "/custom-fields/groups",
    GROUPSID: (id) => `/custom-fields/groups/${id}`,
    TEMPLETE: "/custom-fields/templates",
  },
  RELEASES: {
    UPLOAD: "/releases/upload",
    LIST: "/releases/",
    LATEST: "/releases/latest",
    DOWNLOAD: (id) => `/releases/${id}/download`,
    DELETE: (id) => `/releases/${id}`,
  },

  PROJECTS: {
    // 📌 Projects
    LIST: "/projects",
    CREATE: "/projects",
    DETAIL: (id) => `/projects/${id}`,
    UPDATE: (id) => `/projects/${id}`,
    DELETE: (id) => `/projects/${id}`,

    ADD_MEMBER: (id) => `/projects/${id}/members`,
    REMOVE_MEMBER: (id, userId) => `/projects/${id}/members/${userId}`,

    CONFIG: (id) => `/projects/${id}/config`,
    STATS: (id) => `/projects/${id}/stats`,
    BOARD: (id) => `/projects/${id}/board`,

    // 📌 Tasks
    TASKS_LIST: (projectId) => `/projects/${projectId}/tasks`,
    TASK_CREATE: (projectId) => `/projects/${projectId}/tasks`,

    TASK_DETAIL: (id) => `/projects/tasks/${id}`,
    TASK_UPDATE: (id) => `/projects/tasks/${id}`,
    TASK_DELETE: (id) => `/projects/tasks/${id}`,
    TASK_MOVE: (id) => `/projects/tasks/${id}/move`,

    TASK_COMMENTS_LIST: (id) => `/projects/tasks/${id}/comments`,
    TASK_COMMENT_CREATE: (id) => `/projects/tasks/${id}/comments`,
    COMMENT_UPDATE: (id) => `/projects/comments/${id}`,
    COMMENT_DELETE: (id) => `/projects/comments/${id}`,

    TIME_LOG_CREATE: (taskId) => `/projects/tasks/${taskId}/time-logs`,
    TIME_LOG_LIST: "/projects/time-logs",
    TIME_LOG_DELETE: (id) => `/projects/time-logs/${id}`,

    // 📌 Sprints
    SPRINTS_LIST: (projectId) => `/projects/${projectId}/sprints`,
    SPRINT_CREATE: (projectId) => `/projects/${projectId}/sprints`,
    SPRINT_START: (projectId, sprintId) =>
      `/projects/${projectId}/sprints/${sprintId}/start`,
    SPRINT_COMPLETE: (projectId, sprintId) =>
      `/projects/${projectId}/sprints/${sprintId}/complete`,
  },
  NOTIFICATIONS: {
    BASE: "/notifications",
    UNREAD_COUNT: "/notifications/unread-count",
    MARK_READ: (id) => `/notifications/${id}/read`,
    MARK_ALL_READ: "/notifications/mark-all-read",
    DELETE: (id) => `/notifications/${id}`,
    CLEAR_ALL: "/notifications",
  },
  GOOGLE: {
    OAUTH: {
      CONNECT: "/google/oauth/connect",
      CALLBACK: "/google/oauth/callback",
      STATUS: "/google/oauth/status",
      DISCONNECT: "/google/oauth/disconnect",
      SETTINGS: "/google/oauth/settings",
    },
    GMAIL: {
      MESSAGES: "/google/gmail/messages",
      MESSAGE_DETAIL: (id) => `/google/gmail/messages/${id}`,
      SEND: "/google/gmail/send",
      CONTACT_EMAILS: "/google/gmail/contact-emails",
    },
    CALENDAR: {
      EVENTS: "/google/calendar/events",
      EVENT_DETAIL: (id) => `/google/calendar/events/${id}`,
      SYNC: "/google/calendar/sync-activity",
    },
    CONTACTS: {
      PREVIEW: "/google/contacts/preview",
      IMPORT: "/google/contacts/import",
    },
  },
  SUPPORT: {
    CONTACT: "/support/contact",
    TICKETS: "/support/tickets",
    TICKET_DETAIL: (id) => `/support/tickets/${id}`,
    TICKET_REPLY: (id) => `/support/tickets/${id}/reply`,
    CHAT: "/support/chat",
    CALL: "/support/call",
    CALL_TOKEN: (id) => `/support/tickets/${id}/call-token`,
  },
};

export default API_ENDPOINTS;
